services:
  master:
    image: python-app
    container_name: master
    ports:
      - "9000:9000"
    build:
      context: .
      dockerfile: Dockerfile
    command: "python iteration_1/master.py"

  secondary_1:
    image: python-app
    container_name: secondary_1
    ports:
      - "9001:9001"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONT_NAME: 'secondary_1'
      PORT_NUMBER: 9001
      TIMEOUT: False
    command: "python iteration_1/secondary.py"

  secondary_2:
    image: python-app
    container_name: secondary_2
    ports:
      - "9002:9002"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONT_NAME: 'secondary_2'
      PORT_NUMBER: 9002
      TIMEOUT: TRUE
    command: "python iteration_1/secondary.py"

